name: Run validation
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install npm
        run: |
          npm install
      - name: Run tests
        run: |
          npm run test

      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: image:$(date +%s)
